### ISSUE TITLE
I would like to submit a bug and for a suggestion

### ISSUE THREAD

**Issue by MrAgitming** [mateusak/minecraft-miniature-shader#1]
As a low light and shadow water surface reflection is great, but he has some problems, when you see a river light from the direction parallel to the river, the mirror reflected is the entire river channel (in my perspective) and not the real thing, as shown in the picture.
![Screenshot 2023-01-31 114902](https://user-images.githubusercontent.com/124017444/215658356-c7a26f73-89d2-4a67-8265-678b3e3c1b29.jpg)
And this one,I think that we will have a better feeling if not these lines near the water
![Screenshot 2023-01-31 115115](https://user-images.githubusercontent.com/124017444/215658656-e6eaf395-70b1-4eb0-a5d0-0e96daf299c2.jpg)

**Comment by mateusak** [comment]
I'm not sure I understood the issue, sorry. If you are talking about reflections not matching real-world reflections sometimes, such as when you are under a tree near water, for example, there isn't much that can be done. The reflections are just cheap screen-space reflections; the only information it has is what is on your screen, and therefore it's very prone to distortion and inaccuracies.

It's not possible to solve these issues, but it can be disguised; most other shaders use waves to do it (and there is some primitive form of that in the settings here too), as well as assuming a "sky color" to use when reflection fails. These have other issues, of course; reflecting sky when water is under a roof, for example. Good waves also requires more precise SSR as to not create banding, which impacts performance. It's a complex topic which essentially boils down to what mix of issues you prefer.
